version: 1.0
name: "🌟 Feature Request"
description: Suggest a new feature or improvement for the Ranckors Baggage addon
title: "[Feature] <summary of the suggestion>"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: Describe what you're missing or want to improve.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like the addon to do instead?
      placeholder: |
        Example:
        Add a toggle for Banked Crowns to display them in the UI.

  - type: textarea
    attributes:
      label: Optional UI or behavior suggestions
      description: Describe the desired user experience, UI design, or behavior.

  - type: checkboxes
    attributes:
      label: Affected areas
      description: Which parts of the addon does this impact?
      options:
        - label: Settings Window
        - label: Main Display UI
        - label: Currency Data Handling
        - label: Event Hooks
        - label: SavedVariables

  - type: textarea
    attributes:
      label: Additional context
      description: Any extra thoughts, examples, or mockups?
