name: "💬 General Feedback / Question"
description: Provide feedback, suggestions, or ask a question not covered by other templates
title: "[Feedback] <summary>"
labels: [question, feedback]
body:
  - type: textarea
    attributes:
      label: What’s on your mind?
      description: Share your idea, comment, question, or general feedback here.

  - type: dropdown
    attributes:
      label: Type of input
      options:
        - Suggestion
        - Question
        - Positive Feedback
        - Concern
        - Other

  - type: textarea
    attributes:
      label: Anything else you'd like us to know?
