name: Upload to ESOUI

on:
  push:
    branches:
      - main
    tags: [ 'v*' ]
    paths-ignore:
      - 'LICENSE'
      # - 'README.md'
      - 'CHANGELOG.md'
      # - '.github/**'
      # - '*.md'

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      VERSION: v2.0.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip addon folder
        run: zip -r RanckorsBaggage.zip RanckorsBaggage

      - name: Upload to ESOUI
        if: false
        uses: m00nyONE/esoui-upload@v1
        with:
          api_key: ${{ secrets.ESOUI_ADDON_UPDATE }}
          addon_id: 3933
          version: ${{ env.VERSION }}
          zip_file: RanckorsBaggage.zip
          changelog_file: CHANGELOG.txt

      - name: Update version badge in README
        run: |
          set -euo pipefail
          echo "Updating to VERSION=${VERSION}"

          # Find README.md (case-insensitive) tracked by git
          FILE=$(git ls-files | awk 'tolower($0)=="readme.md"{print; exit}')
          if [ -z "${FILE:-}" ]; then
            FILE=$(git ls-files | grep -i '^readme\.md$' | head -n1 || true)
          fi
          if [ -z "${FILE:-}" ]; then
            echo "README.md not found in repo root. Candidates:" >&2
            git ls-files | grep -i readme || true
            exit 1
          fi
          echo "Target file: $FILE"

          sed -i -E "s/version-v[0-9]+\.[0-9]+\.[0-9]+/version-${VERSION}/" "$FILE"

          if git diff --quiet -- "$FILE"; then
            echo "No version string matched in $FILE" >&2
            grep -n -i 'version' "$FILE" || true
            exit 1
          fi

      - name: Commit README change
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
          message: "docs: bump README to ${VERSION} [skip ci]"
